[package]
name = "sbpf-common"
version.workspace = true
description = "Common types and utilities for SBPF (Solana BPF)"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/blueshift-gg/sbpf"
keywords = ["solana", "bpf", "blockchain"]
categories = ["development-tools"]

[lib]
crate-type = ["cdylib", "lib"]
name = "sbpf_common"

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
phf = "0.13.1"
phf_macros = "0.13.1"

[dev-dependencies]
hex-literal = "1.0.0"
