[package]
name = "sbpf-asm-counter"
version = "0.1.0"
edition = "2021"

[workspace]

[dev-dependencies]
mollusk-svm = "0.7.0"
solana-instruction = "3.0.0"
solana-account = "3.0.0"
solana-address = "1.0.0"
solana-program-error = "3.0.0"
solana-native-token = "3.0.0"
